draft of CleanCartTest.cs
olgayuks/OnlinerByTestFramework pull request #7
Opened 2021-06-22 14:41 UTC by olgayuks

2021-06-25 12:38 UTC, olgayuks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create test for delete test case](https://trello.com/c/Lvc5GAjZ/20-create-test-for-delete-test-case)

2021-06-25 13:02 UTC, mashadolya requested changes

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Constants/Asserts.cs
> +    public static class Asserts
Messages

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Constants/DataForLocator.cs
> +    }
naming

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Pages/CartPage.cs
> +}
formatting

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Pages/CartPage.cs
> +        public string Message()
Get

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Pages/CatalogSamsungPage.cs
> +            return By.XPath($"//*[contains (text(), '{model}')]");
provide more specific locator

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Pages/CatalogSamsungPage.cs
> +            return By.XPath($"//*[contains (text(), '{model}')]");
not sure that we need this method

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Pages/GoodsPage.cs
> +        public GoodsPage ClickButton()
ClickBuyButton

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Steps/ClenCartSteps.cs
> +        public CleanCartSteps OpenCatalog()
path TypeOfGoods as parameter

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Steps/ClenCartSteps.cs
> +        public CleanCartSteps ChooseModel()
see above

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Steps/ClenCartSteps.cs
> +            Assert.StartsWith(Constants.Asserts.DeleteMessage, _cartPage.Message());
atual as parameter 
`MessageShouldBe(expected)`

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Tests/CleanCartTest.cs
> +        public void DeleteSelectedGood_FromCart()
naming

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Tests/CleanCartTest.cs
> +            cleanCartSteps.OpenCatalog()
Move logic with opening goods to the `NavigationBar.cs` 
NavigationBar should be located on `CatalogPage.cs`

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Utils/Waits.cs
> +        public Waits(IWebDriver driver)
static

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Utils/Action.cs
> +    public class Action
static

2021-06-25 13:02 UTC, mashadolya commented on OnlinerByTestFramework/Utils/Waits.cs
> +        public IWebElement GetClickable(By by)
`WaitToBeClickable`

2021-06-25 13:03 UTC, mashadolya requested changes

2021-06-25 13:03 UTC, mashadolya commented on OnlinerByTestFramework/Utils/Waits.cs
> +            _wait = new WebDriverWait(driver, TimeSpan.FromSeconds(3));
Move timeout to config file

2021-06-29 07:56 UTC, mashadolya requested changes

2021-06-29 07:56 UTC, mashadolya commented on .idea/.idea.OnlinerByTestFramework/.idea/encodings.xml
> +</project>
gitignore

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Pages/Base/BasePage.cs
> +            this.locator = locator;
delete this

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Pages/HomePage.cs
> +            Driver.FindElement(CatalogSelector).Click();
create wrapper

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Pages/LoginPage.cs
> +        private static readonly By GoodsTypeSelector = By.XPath("//span[contains(text(),'Телевизоры')]");
Телевизоры to const

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Steps/ClenCartSteps.cs
> +        public CleanCartSteps ChooseModel(string model)
?model

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Steps/ClenCartSteps.cs
> +        public CleanCartSteps AddTheGood()
AddTheGoodToCart

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Tests/CleanCartTest.cs
> +
delete extra line

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Tests/CleanCartTest.cs
> +        [Fact]
add description

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Tests/CleanCartTest.cs
> +}
configure IDE to ad blank line

2021-06-29 07:56 UTC, mashadolya commented on OnlinerByTestFramework/Utils/Waits.cs
> +        public static bool IsElementVisible(IWebDriver driver, By by)
Startup.AppSettings.Configuration.WaitForTimeout as default parameter

2021-07-07 07:14 UTC, Maria-Dolia requested changes

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/CatalogPage.cs
> +    public class CatalogPage : BasePage
Shold be common goods page

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/HomePage.cs
> +        private static readonly By CatalogSelector =
as below

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/LoginPage.cs
> +            new WebElement("Button", Driver, ButtonSelector).Click();
provide specific name

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Wrappers/WebElement.cs
> +
????

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Wrappers/WebElement.cs
> +        private IWebElement _element;
readonly

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Wrappers/WebElement.cs
> +
???

2021-07-07 07:14 UTC, Maria-Dolia commented on OnlinerByTestFramework/Wrappers/WebElement.cs
> +
?

2021-07-10 09:50 UTC, Maria-Dolia requested changes

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Constants/GoodsAndModels.cs
> +            public const string TvModel = "Samsung QE55Q80AAU";
pls move to test

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/CartPage.cs
> +        private static readonly By MessageSelector = By.XPath($" //div[contains(text(),'{GoodsAndModels.Models.TvModel}')]");
do not use hardcoded tv model

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/HomePage.cs
> +        private static readonly By CategoryOfGoodsSelector = By.CssSelector("li[data-bind*='search__result_active']:first-child");
GoodsCategorySelector would be better

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/LoginPage.cs
> +            new WebElement("UsernameInput", Driver, EmailSelector).SendKeys(username);
pls use common naming approach for elements

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Pages/SelectItemPage.cs
> +        public SelectItemPage(IWebDriver driver) : base(driver, ModelSelector, PageName.CatalogPage)
blank line 
hardcoded model

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Steps/AddToCartSteps.cs
> +    public class AddToCart : BaseSteps
naming

2021-07-10 09:50 UTC, Maria-Dolia commented on OnlinerByTestFramework/Steps/AddToCartSteps.cs
> +            _goodsPage = new GoodsPage(driver);
I would recommend to initialize page in the method where it is used

2021-07-10 13:25 UTC, Maria-Dolia approved these changes

2021-07-10 13:40 UTC, merged